### ISSUE TITLE
error in sass syntax highlighting after @media

### ISSUE THREAD

**Issue by jigfox** [tpope/vim-haml#56]
See the following screenshot:

![VIM Screenshot](https://f.cloud.github.com/assets/110414/2491287/83c6f778-b1e5-11e3-813e-2716eb5368fa.png)

[screenshot](https://f.cloud.github.com/assets/110414/2491287/83c6f778-b1e5-11e3-813e-2716eb5368fa.png)

``` sass
h1
  font-size: 10px

p
  font-size: 8px
@media screen and (min-width: 10px)
  h1
    font-size: 200px

body
  height: 100px
```

**Comment by adambair** [comment]
I know I'm late to the party, but I appreciate the fix (just pulled it in today).
