### ISSUE TITLE
o automatically indents by one

### ISSUE THREAD

**Issue by southdesign** [tpope/vim-haml#74]
When I append a new line with `o`, the plugin always indents by one automatically.

E.g. when I want to add 3 divs in jade with classes `.a`, `.b` and `.c` I have to unindent the next lines manually as they are automatically expected to be a child, when I want them to be neighbours only.

Can we make this configurable somehow?

**Comment by tpope** [comment]
I believe `'formatoptions'` lets you tweak the behavior around `o` in particular, if that's what you're after. If you just want to flag those divs as containing no content, I recommend the self closing `.a/` syntax. (It will still generate the proper `<div class="a"></div>` that you expect.)

**Comment by southdesign** [comment]
Thanks, you're right - I was searching for the `'formatoptions'` that trigger the auto-indentation.
Thanks for the keyword!
