### ISSUE TITLE
New plugin to lint all C/C++ functions

### ISSUE THREAD

**Issue by su8** [tpope/vim-haml#83]
Hello Tim,

I'd like to have vim plugin that does C/C++ functions linting, you could start with the standard functions and later expand it to user functions too.

Cheers

**Comment by tpope** [comment]
Is this related to vim-haml in some way I'm not seeing?

**Comment by tpope** [comment]
Well regardless I appreciate the enthusiasm but I have plenty of unfinished projects already.
